const cartActionTypes = {
  ADD_ITEM_TO_CART : 'ADD_ITEM_TO_CART',
  INCREMENT_ITEM_IN_CART: 'INCREMENT_ITEM_IN_CART',
  DECREMENT_ITEM_IN_CART: 'DECREMENT_ITEM_IN_CART',
  REMOVE_ITEM_FROM_CART : 'REMOVE_ITEM_FROM_CART',
  CLEAR_CART: 'CLEAR_CART'
} 

export default cartActionTypes;